### ISSUE TITLE
zlux-app-server requires 'mkdirp', which is not found in 'package.json'

### ISSUE THREAD

**Issue by MKoipish** [zowe/zlux#406]
Hi! I faced with a problem while trying to run zowe, built from a sources. When I start `nodeServer.sh`, error occurs: 
```
Starting node
Debugger listening on ws://127.0.0.1:9229/884ad0b3-ec44-4fdf-a76a-33bd92000676
For help see https://nodejs.org/en/docs/inspector
module.js:550
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\testEnv-WebTEP\web-tep-cap\zlux-app-server\lib\zluxArgs.js:18:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\testEnv-WebTEP\web-tep-cap\zlux-app-server\lib\zluxServer.js:16:64)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

I can see the line `const mkdirp = require('mkdirp');` in the `zlux-app-server/lib/zluxArgs.js`, but I cannot find mkdirp-dependency in `zlux-app-server/package.json`.

**Workaround:** go to `zlux-app-server` and do `npm i mkdirp` explicitly. But this workaround doesn't work for me, since I use `Nodejs v6`, and calling the command above installs Node10-supported module.

**Comment by MKoipish** [comment]
Looks like `npm i mkdirp@0.5.1` works fine on `Nodejs v6`

**Comment by 1000TurquoisePogs** [comment]
I think this is a weird issue where symlinking fails. 
https://github.com/zowe/zlux-app-server/blob/master/package.json#L13 is supposed to establish a symlink which includes mkdirp within, but I have seen it fail before, usually on windows.
But yes this is bad practice, we should explicitly list the modules.

**Comment by 1000TurquoisePogs** [comment]
Fixed now I think.
