### ISSUE TITLE
Authentication failed if LAUNCH_COMPONENT_GROUPS=DESKTOP

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#483]
If you configure `instance.env` to have just
```
LAUNCH_COMPONENT_GROUPS=DESKTOP
```
then the MVD logon fails with this message
```
Authentication failed for 3 types. Types: ["saf","apiml","zss"]
```
There are these msgs in the STDOUT of the ZWE1SV server:
```
2020-07-02 16:08:03.072 <ZWED:66140> ZWESVUSR WARN (org.zowe.zlux.auth.safsso,native array.js:958) APIML login has failed:                             
2020-07-02 16:08:03.075 <ZWED:66140> ZWESVUSR WARN (org.zowe.zlux.auth.safsso,native array.js:958)  { Error: connect ECONNREFUSED 9.20.205.110:7554    
    at Object.exports._errnoException (util.js:1020:11)                                                                                                
    at exports._exceptionWithHostPort (util.js:1043:20)                                                                                                
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)                                                                                    
  code: 'ECONNREFUSED',                                                                                                                                
  errno: 'ECONNREFUSED',                                                                                                                               
  syscall: 'connect',                                                                                                                                  
  address: '9.20.205.110',                                                                                                                             
  port: 7554 }                                                                                                                                         
```

**Comment by John-A-Davies** [comment]
Label should be "server infrastructure"

**Comment by John-A-Davies** [comment]
Log after `ZWED5018I - Initializing with configuration:  ` contains
```
    "mediationLayer": {                                                                              
      "server": {                                                                                    
        "hostname": "9.20.205.110",                                                                  
        "port": 7553,                                                                                
        "isHttps": true,                                                                             
        "gatewayPort": 7554                                                                          
      },                                                                                             
      "enabled": true                                                                                
    },                          
```
