### ISSUE TITLE
The desktop doesn't seem to start with node v6

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#509]
We’ve seen a test failure in our automation when running against node 6. After September we won’t officially be supporting it, but it would be good to fix, so that 1.16 which is the last build that supports it actually works. When we use node 6.17.0 the desktop doesn’t seem to respond and the following error is in the logs:
```
 >>>>>>>>>>>>>>>>>>>>>>>> /ZOWE/tmp/.zowe/logs/appServer-2020-09-11-17-13.log >>>>>>>>>>>>>>>>>>>>>>>
    2020-09-11 17:13:07.043 <ZWED:65860> ZWESVUSR INFO (_zsf.cluster,native array.js:958) ZWED0211I - The number of processors is: 2
    /ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/lib/plugin-loader.js:757
      async loadPlugins() {
            ^^^^^^^^^^^
  
    SyntaxError: Unexpected identifier
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        at Module._compile (module.js:549:28)
        at Object.Module._extensions..js (module.js:586:10)
        at Module.load (module.js:494:32)
        at tryModuleLoad (module.js:453:12)
        at Function.Module._load (module.js:445:3)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/lib/index.js:17:****)
        at Module._compile (module.js:577:32)
        at Object.Module._extensions..js (module.js:586:10)
        at Module.load (module.js:494:32)
        at tryModuleLoad (module.js:453:12)
        at Function.Module._load (module.js:445:3)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/ZOWE/staging/zowe/components/app-server/share/zlux-app-server/lib/zluxArgs.js:14:21)
    Ended with rc=1
```
The full test run is https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/staging/573/consoleFull

**Comment by 1000TurquoisePogs** [comment]
To be fixed within https://github.com/zowe/zlux-server-framework/pull/245

**Comment by 1000TurquoisePogs** [comment]
This should now be fixed. Reopen if not!
