### ISSUE TITLE
Explorer UI apps will fail to load if visiting Desktop with a different domain name than ZOWE_EXPLORER_HOST

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zlux#510]
If we define `ZOWE_EXPLORER_HOST` as `my-domain.com` and access desktop with domain's IP like `https://1.2.3.4:8544`, we can see failure with Chrome:

- explorer ui apps will not load and show as blank screen and javascript errors. If we have developer tool open, the javascript will pause execution with this error:

```
app.min.js:237 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at l (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:237:540)
    at https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:237:450
    at t (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:188496)
    at v (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:187437)
    at t (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:188401)
    at v (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:187437)
    at t (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:188401)
    at v (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:187437)
    at n (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:73:188664)
    at Object.i (https://my-domain.com:7554/ui/v1/explorer-jes/app.min.js:1066:3117)
```

The code where the execution paused is: `function l(){var e=localStorage.getItem(n);return!e||"rtl"!==e&&"ltr"!==e&&"auto"!==e?"ltr":e}`.

`instance.env` is kept as default setting: `ZOWE_EXPLORER_HOST` is defined as `my-domain.com`, but `ZWE_EXTERNAL_HOSTS` and `ZWE_REFERRER_HOSTS` are not defined.

**Comment by jackjia-ibm** [comment]
I found this only happens in Chrome Incognito mode.

**Comment by AdarshdeepCheema** [comment]
cant reproduce it with v1.28. please reopen if it happens again
