### ISSUE TITLE
zssServer initialization failure mxmRC=8, cmsRC=47

### ISSUE THREAD

**Issue by jshewbert** [zowe/zlux#59]
Installing zowe 0.9.4.

zssServer initialization fails with:
MXM status - Failure (name='DOESRV_STD      ', mxmRC=8, cmsRC=47, srvcRC=0, clientVersion=2)
00000000  00000000 00000000 0000002F 00000000  00000000 00000000 00000000          |............................|

**Comment by boudonl** [comment]
Got same error when starting Zowe server embedded in IBM DB2 DEVOPS experience product.The zowe version delivered in my case is 0.9.3

Message during zowe server startup : 

MXM status - Permission denied (name='MXMSRV_STD      ', mxmRC=8, cmsRC=33, srv
00000000  00000000 00000000 00000021 00000000  00000000 00000000 00000000      

When trying to logon than to the zowe gui this message is being logged in the zowe STC 👍 
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined         
    at request.zluxData.webApp.callRootService.then (/u/boudon/zowe/0.9.3/zss-a
    at tryCatcher (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modules/blueb
    at Promise._settlePromiseFromHandler (/u/boudon/zowe/0.9.3/zlux-proxy-serve
    at Promise._settlePromise (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_m
    at Promise._settlePromise0 (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_
    at Promise._settlePromises (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_
    at _drainQueueStep (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modules/
    at _drainQueue (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modules/blue
    at Async._drainQueues (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modul
    at Immediate.Async.drainQueues (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/n
    at tryOnImmediate (timers.js:645:5)                                        
    at processImmediate Ýas _immediateCallback¨ (timers.js:617:5)              

and logon tentative end with 

Authentification failed for 1 type : type ["zss"]

**Comment by 1000TurquoisePogs** [comment]
Now resolved - this line is actually in use, and is going to default to the name "ZWESIS_STD" instead of MXMSRV or DOESRV. 
It will say this when good:
ZIS status - Ok (name='ZWESIS_STD      ', zisRC=4, cmsRC=0, srvcRC=16, clientVersion=2)
