### ISSUE TITLE
error access to zowe cli

### ISSUE THREAD

**Issue by carabanchel** [zowe/zlux#60]
Hi again,
On mainframe the ZOWESVR server sho ws the following msg:

[2018-12-21 08:54:24.552 _unp.utils WARNING] - Callservice: Service call failed.
{ Error: getaddrinfo ENOTFOUND localhost localhost:8544
at errnoException (dns.js:28:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'localhost',
host: 'localhost',
port: 8544 }

Does anyone know where or how would be possible to manage this varriable, parm, etc...???

**Comment by carabanchel** [comment]
+info. 401 unauthorized

**Comment by carabanchel** [comment]
Close because 127.0.0.1 localhost  was included on RESOLVER.

**Comment by carabanchel** [comment]
I got it. Just including 127.0.0.1 localhost in RESOLVER on tcpip parms library 
of mainframe. Not necessary IPL, via "MODIFY RESOLVER,REFRESH" command.
