### ISSUE TITLE
MXM status - Permission denied (name='MXMSRV_STD .... 

### ISSUE THREAD

**Issue by boudonl** [zowe/zlux#68]
Got same error when starting Zowe server embedded in IBM DB2 DEVOPS experience product.The zowe version delivered in my case is 0.9.3

Message during zowe server startup : 

MXM status - Permission denied (name='MXMSRV_STD      ', mxmRC=8, cmsRC=33, srv
00000000  00000000 00000000 00000021 00000000  00000000 00000000 00000000      

When trying to logon than to the zowe gui this message is being logged in the zowe STC 👍 
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined         
    at request.zluxData.webApp.callRootService.then (/u/boudon/zowe/0.9.3/zss-a
    at tryCatcher (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modules/blueb
    at Promise._settlePromiseFromHandler (/u/boudon/zowe/0.9.3/zlux-proxy-serve
    at Promise._settlePromise (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_m
    at Promise._settlePromise0 (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_
    at Promise._settlePromises (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_
    at _drainQueueStep (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modules/
    at _drainQueue (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modules/blue
    at Async._drainQueues (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/node_modul
    at Immediate.Async.drainQueues (/u/boudon/zowe/0.9.3/zlux-proxy-server/js/n
    at tryOnImmediate (timers.js:645:5)                                        
    at processImmediate Ýas _immediateCallback¨ (timers.js:617:5)              

and logon tentative end with 

Authentification failed for 1 type : type ["zss"]

_Originally posted by @boudonl in https://github.com/zowe/zlux/issues/59#issuecomment-457816965_

**Comment by 1000TurquoisePogs** [comment]
I believe this is now documented as being caused by lack of APF authorization of the ZSS cross-memory server (ZWESIS): https://zowe.github.io/docs-site/latest/troubleshoot/troubleshoot-app-framework.html#unable-to-log-in-to-the-zowe-desktop
