### ISSUE TITLE
Error during startup of ZSS Server in 1.0

### ISSUE THREAD

**Issue by hogstrom** [zowe/zlux#71]
Getting this during startup of 1.0.0 build 505

```
[2019-02-04 18:10:15.459 _zsf.bootstrap WARNING] - Implementation defaults for zosmf was not an object, or did not contain a plugins attribute. Other criteria f
[2019-02-04 18:10:15.460 _zsf.bootstrap WARNING] - Authentication plugin was found which was not requested in the server configuration file's dataserviceAuthent
[2019-02-04 18:10:15.460 _zsf.bootstrap WARNING] - /SYSTEM/var/zowe/1.0.0/zosmf-auth points to an invalid plugin definition, skipping                           
Error: Plugin org.zowe.zlux.auth.zosmf invalid                                                                                                                  
    at makePlugin (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/plugin-loader.js:508:11)                                                                    
    at PluginLoader.installPlugins (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/plugin-loader.js:623:24)                                                   
    at PluginLoader.loadPlugins (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/plugin-loader.js:595:10)                                                      
    at Server.<anonymous> (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/index.js:177:23)                                                                    
    at next (native)                                                                                                                                            
    at tryCatcher (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)                                                 
    at PromiseSpawn._promiseFulfilled (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)                       
    at Promise._settlePromise (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:574:26)                                 
    at Promise._settlePromise0 (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:614:10)                                
    at Promise._settlePromises (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:694:18)                                
    at _drainQueueStep (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)                                          
    at _drainQueue (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)                                               
    at Async._drainQueues (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)                                        
    at Immediate.Async.drainQueues (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:17:14)                               
    at tryOnImmediate (timers.js:645:5)                                                                                                                         
    at processImmediate [as _immediateCallback] (timers.js:617:5)                                                                                               
[2019-02-04 18:10:15.461 _zsf.bootstrap INFO] - Failed to load org.zowe.zlux.auth.zosmf: Error: Plugin org.zowe.zlux.auth.zosmf invalid                         
[2019-02-04 18:10:15.462 _zsf.bootstrap WARNING] - Implementation defaults for fallback was not an object, or did not contain a plugins attribute. Other criteri
[2019-02-04 18:10:15.462 _zsf.bootstrap WARNING] - Authentication plugin was found which was not requested in the server configuration file's dataserviceAuthent
[2019-02-04 18:10:15.462 _zsf.bootstrap WARNING] - /SYSTEM/var/zowe/1.0.0/zlux-server-framework/plugins/trivial-auth points to an invalid plugin definition, ski
Error: Plugin org.zowe.zlux.auth.trivial invalid                                                                                                                
    at makePlugin (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/plugin-loader.js:508:11)                                                                    
    at PluginLoader.installPlugins (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/plugin-loader.js:623:24)                                                   
    at PluginLoader.loadPlugins (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/plugin-loader.js:595:10)                                                      
    at Server.<anonymous> (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/lib/index.js:177:23)                                                                    
    at next (native)                                                                                                                                            
    at tryCatcher (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)                                                 
    at PromiseSpawn._promiseFulfilled (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)                       
    at Promise._settlePromise (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:574:26)                                 
    at Promise._settlePromise0 (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:614:10)                                
    at Promise._settlePromises (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:694:18)                                
    at _drainQueueStep (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)                                          
    at _drainQueue (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)                                               
    at Async._drainQueues (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)                                        
    at Immediate.Async.drainQueues (/SYSTEM/var/zowe/1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:17:14)                               
    at tryOnImmediate (timers.js:645:5)                                                                                                                         
    at processImmediate [as _immediateCallback] (timers.js:617:5)                                                                                               
[2019-02-04 18:10:15.462 _zsf.bootstrap INFO] - Failed to load org.zowe.zlux.auth.trivial: Error: Plugin org.zowe.zlux.auth.trivial invalid     
```

**Comment by 1000TurquoisePogs** [comment]
This means "you requested an auth plugin which isnt needed by anyone, so we're not loading it" but the mechanism to not load it is to throw... there are better ways to do this.
The reason this even happens by default is that we load the plugins in the assumption that someone might want them with minimal configuration change... Basically to uncomment this like for zosmf for example:
https://github.com/zowe/zlux-app-server/blob/master/config/zluxserver.json#L56
But, as we make the add&remove procedure for plugins easy as can be, then we'll have no reason to do this at all.

**Comment by 1000TurquoisePogs** [comment]
Fixed within https://github.com/zowe/zlux-server-framework/pull/94 now.
